CREATE TABLE `CP` (
  `ISIN_CODE` VARCHAR(255) NOT NULL,
  `ISSUER_CODE` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `BOND_UNIT` INT NOT NULL,
  `AMOUNT` INT NOT NULL,
  `DATE` DATE NOT NULL,
  `CREATED_AT` DATE NOT NULL,
  `UPDATED_AT` DATE NOT NULL,
  PRIMARY KEY(ISIN_CODE,DATE)
);