spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HOFURI
    username: HOFURI_PROD
    password: ${MYSQL_PASSWORD}

server:
  port: ${APP_PORT}

selenium:
  host: ${SELENIUM_HOST}
  options: --no-sandbox,--disable-gpu,--disable-dev-shm-usage,--headless

cron:
  get-cp-balance: ${CRON_GET_CP_BALANCE}

logging:
  file:
    name: ${LOG_PATH}
