spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HOFURI
    username: HOFURI_DEV
    password: ${MYSQL_PASSWORD}

server:
  port: ${APP_PORT}

selenium:
  host: ${SELENIUM_HOST}

cron:
  get-cp-balance: ${CRON_GET_CP_BALANCE}
